/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examensimulacro1;

import javax.swing.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author IzanPerezDímas
 */
public class JFrameEj1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public JFrameEj1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        this.setResizable(false);

        jPanel1 = new javax.swing.JPanel();
        jLabelMoneda = new javax.swing.JLabel();
        jLabelConvertirMoneda = new javax.swing.JLabel();
        jLabelDolar = new javax.swing.JLabel();
        jLabelAMoneda = new javax.swing.JLabel();
        jLabelEuro = new javax.swing.JLabel();
        jButtonConvertirMoneda = new javax.swing.JButton();
        jTextFieldEuro = new javax.swing.JTextField();
        jTextFieldDolar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelLongitud = new javax.swing.JLabel();
        jLabelConvertirLongitud = new javax.swing.JLabel();
        jLabelMile = new javax.swing.JLabel();
        jLabelALongitud = new javax.swing.JLabel();
        jLabelKilometro = new javax.swing.JLabel();
        jButtonConvertirLongitud = new javax.swing.JButton();
        jTextFieldMile = new javax.swing.JTextField();
        jTextFieldKilometro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelMasa = new javax.swing.JLabel();
        jLabelConvertirMasa = new javax.swing.JLabel();
        jLabelPund = new javax.swing.JLabel();
        jLabelAMasa = new javax.swing.JLabel();
        jLabelKilogramo = new javax.swing.JLabel();
        jButtonConvertirMasa = new javax.swing.JButton();
        jTextFieldPound = new javax.swing.JTextField();
        jTextFieldKilogramo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jLabelMoneda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMoneda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMoneda.setText("Moneda");

        jLabelConvertirMoneda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelConvertirMoneda.setText("Quiero convertir:");

        jTextFieldDolar.setText("1.00");
        jTextFieldDolar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                checkNumeroDecimal(e, jTextFieldDolar);
            }
        });

        jLabelDolar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDolar.setText("U.S. dollar (USD)");

        jLabelAMoneda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAMoneda.setText("A:");

        jTextFieldEuro.setText("0.82");
        jTextFieldEuro.setEditable(false);

        jLabelEuro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEuro.setText("Euro (EUR)");

        jButtonConvertirMoneda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonConvertirMoneda.setText("CONVERTIR");
        jButtonConvertirMoneda.addActionListener(evt -> convertirUnidades(jTextFieldDolar, jTextFieldEuro, 0.82));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelMoneda)
                                        .addComponent(jLabelConvertirMoneda)
                                        .addComponent(jLabelDolar)
                                        .addComponent(jLabelAMoneda)
                                        .addComponent(jLabelEuro)
                                        .addComponent(jButtonConvertirMoneda)
                                        .addComponent(jTextFieldEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(12, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldDolar)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelMoneda)
                                .addGap(0, 0, 0)
                                .addComponent(jLabelConvertirMoneda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDolar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAMoneda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEuro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConvertirMoneda)
                                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1);

        jLabelLongitud.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelLongitud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelLongitud.setText("Longitud");

        jLabelConvertirLongitud.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelConvertirLongitud.setText("Quiero convertir:");

        jTextFieldMile.setText("1.00");
        jTextFieldMile.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                checkNumeroDecimal(e, jTextFieldMile);
            }
        });

        jLabelMile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMile.setText("Mile (ml)");

        jLabelALongitud.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelALongitud.setText("A:");

        jLabelKilometro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelKilometro.setText("Kilometro (Km)");

        jTextFieldKilometro.setText("1.61");
        jTextFieldKilometro.setEditable(false);

        jButtonConvertirLongitud.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonConvertirLongitud.setText("CONVERTIR");
        jButtonConvertirLongitud.addActionListener(evt -> convertirUnidades(jTextFieldMile, jTextFieldKilometro, 1.61));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldMile)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelLongitud)
                                                        .addComponent(jLabelConvertirLongitud)
                                                        .addComponent(jLabelMile)
                                                        .addComponent(jLabelALongitud)
                                                        .addComponent(jLabelKilometro)
                                                        .addComponent(jButtonConvertirLongitud))
                                                .addGap(0, 57, Short.MAX_VALUE))
                                        .addComponent(jTextFieldKilometro))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelLongitud)
                                .addGap(0, 0, 0)
                                .addComponent(jLabelConvertirLongitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelALongitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelKilometro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldKilometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConvertirLongitud)
                                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2);

        jLabelMasa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMasa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMasa.setText("Masa");

        jLabelConvertirMasa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelConvertirMasa.setText("Quiero convertir:");

        jTextFieldPound.setText("1.00");
        jTextFieldPound.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                checkNumeroDecimal(e, jTextFieldPound);
            }
        });

        jLabelPund.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPund.setText("Pound (lb)");

        jLabelAMasa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAMasa.setText("A:");

        jLabelKilogramo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelKilogramo.setText("Kilogramo (Kg)");

        jTextFieldKilogramo.setText("0.45");
        jTextFieldKilogramo.setEditable(false);

        jButtonConvertirMasa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonConvertirMasa.setText("CONVERTIR");
        jButtonConvertirMasa.addActionListener(evt -> convertirUnidades(jTextFieldPound, jTextFieldKilogramo, 0.45));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPound)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelMasa)
                                                        .addComponent(jLabelConvertirMasa)
                                                        .addComponent(jLabelPund)
                                                        .addComponent(jLabelAMasa)
                                                        .addComponent(jLabelKilogramo)
                                                        .addComponent(jButtonConvertirMasa))
                                                .addGap(0, 57, Short.MAX_VALUE))
                                        .addComponent(jTextFieldKilogramo))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelMasa)
                                .addGap(0, 0, 0)
                                .addComponent(jLabelConvertirMasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPund)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAMasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelKilogramo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldKilogramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConvertirMasa)
                                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>                        

    private void convertirUnidades(JTextField campoOrigen, JTextField campoResultado, double equivalencia) {
        try {
            campoResultado.setText(String.valueOf(Double.parseDouble(campoOrigen.getText()) * equivalencia));
        } catch (NumberFormatException ignore) {

        }
    }

    private void checkNumeroDecimal(KeyEvent e, JTextField textField) {
        char caracter = e.getKeyChar();
        if (!((Character.isDigit(caracter) || (caracter == '.') || caracter == KeyEvent.VK_BACK_SPACE || caracter == KeyEvent.VK_DELETE) &&
                (textField.getText().isEmpty() || (caracter != '.' || textField.getText().indexOf('.') == -1)))) {
            e.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEj1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEj1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonConvertirLongitud;
    private javax.swing.JButton jButtonConvertirMasa;
    private javax.swing.JButton jButtonConvertirMoneda;
    private javax.swing.JTextField jTextFieldDolar;
    private javax.swing.JTextField jTextFieldEuro;
    private javax.swing.JTextField jTextFieldKilogramo;
    private javax.swing.JTextField jTextFieldKilometro;
    private javax.swing.JTextField jTextFieldMile;
    private javax.swing.JTextField jTextFieldPound;
    private javax.swing.JLabel jLabelALongitud;
    private javax.swing.JLabel jLabelAMasa;
    private javax.swing.JLabel jLabelAMoneda;
    private javax.swing.JLabel jLabelConvertirLongitud;
    private javax.swing.JLabel jLabelConvertirMasa;
    private javax.swing.JLabel jLabelConvertirMoneda;
    private javax.swing.JLabel jLabelDolar;
    private javax.swing.JLabel jLabelEuro;
    private javax.swing.JLabel jLabelKilogramo;
    private javax.swing.JLabel jLabelKilometro;
    private javax.swing.JLabel jLabelLongitud;
    private javax.swing.JLabel jLabelMasa;
    private javax.swing.JLabel jLabelMile;
    private javax.swing.JLabel jLabelMoneda;
    private javax.swing.JLabel jLabelPund;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration                   
}
