/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examensimulacro1;

import javax.swing.*;
import java.awt.*;
import java.util.EventListener;

/**
 *
 * @author IzanPerezDímas
 */
public class JFrameEj2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEj2
     */
    public JFrameEj2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroupColor = new javax.swing.ButtonGroup();
        buttonGroupFondo = new javax.swing.ButtonGroup();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jPanelColorYFondo = new javax.swing.JPanel();
        jLabelColor = new javax.swing.JLabel();
        jRadioButtonNegro = new javax.swing.JRadioButton();
        jRadioButtonBlanco = new javax.swing.JRadioButton();
        jLabelFondo = new javax.swing.JLabel();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jRadioButtonVerde = new javax.swing.JRadioButton();
        jRadioButtonAzul = new javax.swing.JRadioButton();
        jPanelMostrar = new javax.swing.JPanel();
        jLabelMostrar = new javax.swing.JLabel();
        jTextFieldMostrar = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        jPanelFormato = new javax.swing.JPanel();
        jLabelFormato = new javax.swing.JLabel();
        jCheckBoxNegrita = new javax.swing.JCheckBox();
        jCheckBoxCursiva = new javax.swing.JCheckBox();
        jPanelUltimaAccion = new javax.swing.JPanel();
        jLabelUltimaAccion = new javax.swing.JLabel();
        jTextFieldUltimaAccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea.setColumns(20);
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setEditable(false);
        jScrollPane.setViewportView(jTextArea);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        jLabelColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelColor.setText("Color texto:");

        buttonGroupColor.add(jRadioButtonNegro);
        jRadioButtonNegro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonNegro.setText("Negro");
        jRadioButtonNegro.addActionListener(evt -> {
            mostrarTexto();
            jTextFieldUltimaAccion.setText("Color negro seleccionado");
        });

        buttonGroupColor.add(jRadioButtonBlanco);
        jRadioButtonBlanco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonBlanco.setSelected(true);
        jRadioButtonBlanco.setText("Blanco");
        jRadioButtonBlanco.addActionListener(evt -> {
            mostrarTexto();
            jTextFieldUltimaAccion.setText("Color blanco seleccionado");
        });

        jLabelFondo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFondo.setText("Fondo:");

        buttonGroupFondo.add(jRadioButtonRojo);
        jRadioButtonRojo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonRojo.setText("Rojo");
        jRadioButtonRojo.addActionListener(evt -> {
            mostrarTexto();
            jTextFieldUltimaAccion.setText("Fondo rojo seleccionado");
        });

        buttonGroupFondo.add(jRadioButtonVerde);
        jRadioButtonVerde.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonVerde.setText("Verde");
        jRadioButtonVerde.addActionListener(evt -> {
            mostrarTexto();
            jTextFieldUltimaAccion.setText("Fondo verde seleccionado");
        });

        buttonGroupFondo.add(jRadioButtonAzul);
        jRadioButtonAzul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonAzul.setSelected(true);
        jRadioButtonAzul.setText("Azul");
        jRadioButtonAzul.addActionListener(evt -> {
            mostrarTexto();
            jTextFieldUltimaAccion.setText("Fondo azul seleccionado");
        });

        javax.swing.GroupLayout jPanelColorYFondoLayout = new javax.swing.GroupLayout(jPanelColorYFondo);
        jPanelColorYFondo.setLayout(jPanelColorYFondoLayout);
        jPanelColorYFondoLayout.setHorizontalGroup(
                jPanelColorYFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelColorYFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelColorYFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelColor)
                                        .addComponent(jLabelFondo)
                                        .addGroup(jPanelColorYFondoLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanelColorYFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jRadioButtonBlanco)
                                                        .addComponent(jRadioButtonNegro)
                                                        .addComponent(jRadioButtonVerde)
                                                        .addComponent(jRadioButtonRojo)
                                                        .addComponent(jRadioButtonAzul))))
                                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelColorYFondoLayout.setVerticalGroup(
                jPanelColorYFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelColorYFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelColor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNegro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonBlanco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelFondo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonVerde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonRojo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAzul)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelColorYFondo, java.awt.BorderLayout.LINE_START);

        jLabelMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMostrar.setText("Introduce el texto a mostrar:");

        jTextFieldMostrar.setText("Hola esto es una prueba");

        jButtonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonMostrar.setText("MOSTRAR");
        jButtonMostrar.addActionListener(evt -> {
            if (jTextFieldMostrar.getText().isEmpty()) {
                jTextFieldUltimaAccion.setText("");
                JOptionPane.showMessageDialog(this, "El mensaje no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                mostrarTexto();
            }
        });

        javax.swing.GroupLayout jPanelMostrarLayout = new javax.swing.GroupLayout(jPanelMostrar);
        jPanelMostrar.setLayout(jPanelMostrarLayout);
        jPanelMostrarLayout.setHorizontalGroup(
                jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMostrarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonMostrar)
                                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelMostrarLayout.setVerticalGroup(
                jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMostrarLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelMostrar)
                                        .addComponent(jTextFieldMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonMostrar))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMostrar, java.awt.BorderLayout.PAGE_START);

        jLabelFormato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFormato.setText("Formato texto:");

        jCheckBoxNegrita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxNegrita.setSelected(true);
        jCheckBoxNegrita.setText("Negrita");
        jCheckBoxNegrita.addActionListener(evt -> {
            mostrarTexto();
            if (jCheckBoxCursiva.isSelected()) {
                jTextFieldUltimaAccion.setText("Negrita y cursiva seleccionada");
            } else {
                jTextFieldUltimaAccion.setText("Negrita seleccionada");
            }
        });

        jCheckBoxCursiva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxCursiva.setSelected(true);
        jCheckBoxCursiva.setText("Cursiva");
        jCheckBoxCursiva.addActionListener(evt -> {
            mostrarTexto();
            if (jCheckBoxNegrita.isSelected()) {
                jTextFieldUltimaAccion.setText("Negrita y cursiva seleccionada");
            } else {
                jTextFieldUltimaAccion.setText("Cursiva seleccionada");
            }
        });

        javax.swing.GroupLayout jPanelFormatoLayout = new javax.swing.GroupLayout(jPanelFormato);
        jPanelFormato.setLayout(jPanelFormatoLayout);
        jPanelFormatoLayout.setHorizontalGroup(
                jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFormatoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelFormatoLayout.createSequentialGroup()
                                                .addComponent(jLabelFormato)
                                                .addGap(0, 4, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormatoLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCheckBoxCursiva, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jCheckBoxNegrita, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addContainerGap())
        );
        jPanelFormatoLayout.setVerticalGroup(
                jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelFormatoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelFormato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxNegrita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxCursiva)
                                .addContainerGap(144, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFormato, java.awt.BorderLayout.LINE_END);

        jLabelUltimaAccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUltimaAccion.setText("Última acción:");

        jTextFieldUltimaAccion.setEnabled(false);

        javax.swing.GroupLayout jPanelUltimaAccionLayout = new javax.swing.GroupLayout(jPanelUltimaAccion);
        jPanelUltimaAccion.setLayout(jPanelUltimaAccionLayout);
        jPanelUltimaAccionLayout.setHorizontalGroup(
                jPanelUltimaAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelUltimaAccionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelUltimaAccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUltimaAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelUltimaAccionLayout.setVerticalGroup(
                jPanelUltimaAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelUltimaAccionLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanelUltimaAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelUltimaAccion)
                                        .addComponent(jTextFieldUltimaAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelUltimaAccion, java.awt.BorderLayout.PAGE_END);

        pack();

        mostrarTexto();
    }// </editor-fold>

    private void mostrarTexto() {
        if (jRadioButtonNegro.isSelected()) {
            jTextArea.setForeground(Color.BLACK);
        } else {
            jTextArea.setForeground(Color.WHITE);
        }
        if (jRadioButtonVerde.isSelected()) {
            jTextArea.setBackground(Color.GREEN);
        } else if (jRadioButtonRojo.isSelected()) {
                jTextArea.setBackground(Color.RED);
        } else {
            jTextArea.setBackground(Color.BLUE);
        }
        if (jCheckBoxNegrita.isSelected() && jCheckBoxCursiva.isSelected()) {
            jTextArea.setFont(new java.awt.Font("Segoe UI", Font.BOLD | Font.ITALIC, 18));
        } else if (jCheckBoxNegrita.isSelected()) {
            jTextArea.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 18));
        } else if (jCheckBoxCursiva.isSelected()) {
            jTextArea.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 18)); // NOI18N
        } else {
            jTextArea.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 18)); // NOI18N
        }
        jTextArea.setText(jTextFieldMostrar.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEj2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroupColor;
    private javax.swing.ButtonGroup buttonGroupFondo;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JCheckBox jCheckBoxCursiva;
    private javax.swing.JCheckBox jCheckBoxNegrita;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFormato;
    private javax.swing.JLabel jLabelMostrar;
    private javax.swing.JLabel jLabelUltimaAccion;
    private javax.swing.JPanel jPanelColorYFondo;
    private javax.swing.JPanel jPanelFormato;
    private javax.swing.JPanel jPanelMostrar;
    private javax.swing.JPanel jPanelUltimaAccion;
    private javax.swing.JRadioButton jRadioButtonAzul;
    private javax.swing.JRadioButton jRadioButtonBlanco;
    private javax.swing.JRadioButton jRadioButtonNegro;
    private javax.swing.JRadioButton jRadioButtonRojo;
    private javax.swing.JRadioButton jRadioButtonVerde;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldMostrar;
    private javax.swing.JTextField jTextFieldUltimaAccion;
    // End of variables declaration
}
